version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@sanity/client"
    versions:
    - 2.1.4
    - 2.2.6
    - 2.7.0
    - 2.7.1
  - dependency-name: "@sanity/image-url"
    versions:
    - 0.140.19
    - 0.140.20
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
